version: 2
updates:
  # Monitor Python dependencies
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
    open-pull-requests-limit: 10
    reviewers:
      - "GuiDev-01"
    assignees:
      - "GuiDev-01"
    commit-message:
      prefix: "deps"
      include: "scope"
    labels:
      - "dependencies"
      - "security"
    
  # Monitor GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
    open-pull-requests-limit: 5
    reviewers:
      - "GuiDev-01"
    assignees:
      - "GuiDev-01"
    commit-message:
      prefix: "ci"
    labels:
      - "ci/cd"
      - "dependencies"
    
  # Monitor Docker dependencies
  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
    open-pull-requests-limit: 5
    reviewers:
      - "GuiDev-01"
    assignees:
      - "GuiDev-01"
    commit-message:
      prefix: "docker"
    labels:
      - "docker"
      - "dependencies"
