services:
  api:
    build: .
    container_name: orionjobs-api
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - ENVIRONMENT=development
      - COLLECT_MAX_PAGES=1
      - COLLECT_SLEEP_SECONDS=1
      - COLLECT_ADZUNA_MAX_REQUESTS=5
    volumes:
      - .:/app
    restart: unless-stopped
    command: >
      sh -c "
        echo 'Running migrations...' &&
        alembic upgrade head &&
        echo 'Starting OrionJobs API...' &&
        uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
      "