"""Add API cache table

Revision ID: b540b629815b
Revises: 4636fb6369da
Create Date: 2025-09-22 22:47:08.779148

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b540b629815b'
down_revision: Union[str, Sequence[str], None] = '4636fb6369da'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade():
    op.create_table(
        'api_cache',
        sa.Column('id', sa.Integer, primary_key=True, autoincrement=True),
        sa.Column('query', sa.String, nullable=False),
        sa.Column('country', sa.String, nullable=False),
        sa.Column('response', sa.JSON, nullable=False),
        sa.Column('created_at', sa.DateTime, server_default=sa.func.now())
    )


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
